export const enum TipoCate {
  Pan = 'Pan',
  Cereales = 'Cereales',
  Pastas = 'Pastas',
  Arroz = 'Arroz',
  Verduras = 'Verduras',
  Frutas = 'Frutas',
  Leche = 'Leche',
  Cacao = 'Cacao',
  Yogur = 'Yogur',
  Queso = 'Queso',
  Carne = 'Carne',
  Pollo = 'Pollo',
  Pescado = 'Pescado',
  Huevos = 'Huevos',
  Aceite = 'Aceite',
  Galletas = 'Galletas',
  Jugo = 'Jugo',
  Gaseosa = 'Gaseosa',
  Harina = 'Harina',
  Azucar = 'Azucar',
  Sal = 'Sal',
  Manteca = 'Manteca',
  Te = 'Te',
  Cafe = 'Cafe',
  Yerba = 'Yerba',
  Otros = 'Otros'
}
